name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: npm install

    - name: Compile contracts
      run: ./node_modules/.bin/truffle build

    - name: Run test
      run: |
        ./node_modules/.bin/ganache-cli &
        ./node_modules/.bin/truffle test
